version: '3.1'
services:
  book-exchange-service:
    container_name: book-exchange-service
    networks:
      - book-exchange-network
    image: markojerkic/book-exchange-service:latest
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=bookdb
      - DB_PORT=5432
      #- CORS_ORIGINS=http://34.89.240.97:443
    volumes:
      - service_volume:/home/images
    depends_on:
      - bookdb
  book-exchange-front:
    image: markojerkic/book-exchange-front
    container_name: book-exchange-front
    networks:
      - book-exchange-network
    ports:
      - 80:80
    depends_on:
      - book-exchange-service
  bookdb:
    image: postgres
    container_name: bookdb
    networks:
      - book-exchange-network
    environment:
      - POSTGRES_USER=bookuser
      - POSTGRES_PASSWORD=bookpassword
      - POSTGRES_DB=bookdb
      - PGDATA=/var/lib/postgresql/data/dbdata
    ports:
      - 5432:5432
      - 5700:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
volumes:
  dbdata:
  service_volume:
networks:
  book-exchange-network:
